Create main settings form
ApacheEx/drupal-hybridauth pull request #1
Opened 2020-01-25 14:02 UTC by Matveycom

2020-01-25 14:06 UTC, VladBo requested changes
$this->t()

2020-01-25 14:06 UTC, VladBo commented on src/Form/HybridauthAdminSettings.php
> +        'email' => t('Email address'),
$this->t()

2020-01-25 14:18 UTC, ApacheEx requested changes

2020-01-25 14:18 UTC, ApacheEx commented on src/Form/HybridauthAdminSettings.php
> +   * Constructs a new XmlSitemapCustomAddForm object.
let's fix description

2020-01-25 14:18 UTC, ApacheEx commented on src/Form/HybridauthAdminSettings.php
> +    $module_exist_token = $this->moduleHandler->moduleExists('token');
let's rename to `$token_exists`

2020-01-25 14:18 UTC, ApacheEx commented on src/Form/HybridauthAdminSettings.php
> +      '#disabled' => !$this->moduleHandler->moduleExists('realname'),
let's remove support of realname at all

2020-01-25 14:18 UTC, ApacheEx commented on src/Form/HybridauthAdminSettings.php
> +    $options = [
useless - let's use it without variable

2020-01-25 14:18 UTC, ApacheEx commented on src/Form/HybridauthAdminSettings.php
> +    $config = $this->config('hybridauth.settings');
let's have a config for it

2020-01-28 08:26 UTC, ApacheEx approved these changes

2020-01-28 08:28 UTC, merged